name: Laravel CI
on: [push]
jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create .env
        run: php -r "file_exists('.env') || copy('.env.ci', '.env');"
      - name: Install composer depencencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Create DB and schemas
        run: |
          mkdir -p database
          touch database/database.sqlite
          php artisan migrate --seed
      - name: Run PHPUnit
        run: vendor/bin/phpunit
